kind: Service
apiVersion: v1
metadata:
  name: d-nginx
  #namespace: d-dev
spec:
  selector:
    app: d-nginx
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer


