apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: staging
  name: b-staging-reconciler-binding
subjects:
  - kind: ServiceAccount
    name: ns-reconciler-staging
    namespace: config-management-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: b-staging-manager
