apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: staging
  name: config-sync-role
rules:
  - apiGroups: [""]
    resources: ["services", "pods"]
    verbs: ["get", "list", "create", "watch", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "watch", "update", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings", "roles"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  # - apiGroups: [""]
  #   resources: ["serviceaccounts"]
  #   verbs: ["*"]
