apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-nginx-deployment
  namespace: staging
  labels:
    app: b-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: b-nginx
  template:
    metadata:
      labels:
        app: b-nginx
    spec:
      containers:
      - name: b-nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80