kind: Service
apiVersion: v1
metadata:
  name: b-nginx
  namespace: b-staging
spec:
  selector:
    app: b-nginx
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer


