apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-reader-binding
subjects:
  - kind: ServiceAccount
    name: ns-reconciler-root-sync  # Update based on your RootSync or RepoSync reconciler ServiceAccount
    namespace: config-management-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-reader
