apiVersion: v1
kind: Namespace
metadata:
  name: a-dev
---
kind: Service
apiVersion: v1
metadata:
  name: a-nginx
  namespace: a-dev
spec:
  selector:
    app: a-nginx
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer


