apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: c-prod
  name: c-prod-manager
rules:
  - apiGroups: [""]
    resources: ["services","pods"]
    verbs: ["get", "list","watch", "create", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create","watch", "update", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings", "roles"]
    verbs: ["get", "watch","list"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["*"]