apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  
  name: rootsyncstaging
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/Roopa-Sri3/kubernetes.git
    branch: main
    dir: /APPLICATIONS/STAGING/b-nginx
    auth: none