apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  
  name: rootsyncstaging
  namespace: staging
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/Roopa-Sri3/kubernetes.git
    branch: prod
    dir: /APPLICATIONS/STAGING/b-nginx
    auth: none