apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  
  name: rootsyncprod
  namespace: prod
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/Roopa-Sri3/kubernetes.git
    branch: dev
    dir: /APPLICATIONS/PROD/c-nginx
    auth: none