apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: c-prod
  name: c-prod-reconciler-binding
subjects:
  - kind: ServiceAccount
    name: ns-reconciler-c-prod-repo-sync-prod-14
    namespace: config-management-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: c-prod-manager
