apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: prod
  name: config-sync-rolebinding
subjects:
  - kind: ServiceAccount
    name: ns-reconciler-prod-reposyncprod-12
    namespace: config-management-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-sync-role
